app/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField,ValidationError
from wtforms.validators import Required

class PostForm(FlaskForm):
    title = StringField('Title',validators=[Required()])
    body = TextAreaField('Text',validators=[Required()])
    submit = SubmitField("Submit")


class CommentForm(FlaskForm):
    body = TextAreaField('Text',validators=[Required()])
    submit = SubmitField("Submit")

app/blog/__init__.py
from flask import Blueprint
blog = Blueprint('blog',__name__)
from . import views

app/blog/views.py
from flask import render_template,request,redirect,url_for,abort,flash
from . import blog
from flask_login import login_required,current_user
from ..models import User,Blog,Comment
from .forms import PostForm ,CommentForm
from .. import db

#Create a blog
@blog.route('/create',methods = ['GET','POST'])
@login_required
def create_post():
    post_form = PostForm()
    if post_form.validate_on_submit():
        post = Blog(title = post_form.title.data,
                    body = post_form.body.data,
                    user_id = current_user.id)
        db.session.add(post)
        db.session.commit()
        flash('Post saved')
        return redirect(url_for('main.index'))
    return render_template('blog/create_post.html', post_form=post_form)

# VIEW A POST
@blog.route('blog/<int:post_id>')
def post(post_id):
    post = Blog.query.get_or_404(post_id)
    return render_template('blog/post.html', title =post.title, date = post.posted, post = post)

@blog.route('blog/<int:post_id>/update', methods = ['GET', 'POST'])
@login_required
def update(post_id):
    '''
    function to update post
    '''
    post = Blog.query.get_or_404(post_id)
    if post.author!=current_user:
        #403 error is forbidden
        abort(403)
    post_form  = PostForm()

    if post_form.validate_on_submit():
        post.title = post_form.title.data
        post.body = post_form.body.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('blog.post', post_id=post.id))

    elif request.method == 'GET':
        post_form.title.data = post.title
        post_form.body.data = post.body

    return render_template('blog/create_post.html',title = 'Updating', post_form = post_form)


@blog.route('blog/<int:post_id>/delete', methods = ['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Blog.query.get_or_404(post_id)
    if post.author!=current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()

    flash('Post deleted.')
    return redirect(url_for('main.index'))


@blog.route('comment/<int:id>')
def comment(id):
    post =Blog.query.filter_by(id=id).first()
    return render_template('blog/view_comments.html', post = post,id=id)

@blog.route('/blog/<int:id>/comment', methods = ['GET','POST'])
@login_required
def new_comment(id):
    # import pdb;pdb.set_trace()
    comments = Comment.query.filter_by(id=id).all()
    form = CommentForm()

    if form.validate_on_submit():
        comment = Comment(body = form.body.data,
                            blog_id = id,
                          author_id= current_user.id)
        db.session.add(comment)
        db.session.commit()
        flash('Comments added successfuly!')
        return redirect(url_for('.comment', id=id))

    # from pprint import pprint
    # pprint(post)
    # import pdb;pdb.set_trace()
    return render_template('blog/comment.html',comments =comments, comment_form=form)

@blog.route('comment/<int:id>/delete', methods = ['GET', 'POST'])
@login_required
def delete_comment(id):
    comments = Comment.query.filter_by(id=id).all()
    # if post.author!=current_user:
    #     abort(403)

    # db.session.delete(comment)
    # db.session.commit()

    flash('Comment deleted.')
    return redirect(url_for('main.index'))

app/templates/blog/comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container"> 
        <div class="row">
          <div class= "col-md-2"> </div>
          <div class="col-md-8">
          <!-- Create comment form -->
          {{wtf.quick_form(comment_form)}}
         </div>
         <div clas="col-md-2"> </div>
        </div>
    </div>
    

{% endblock %}

app/templates/blog/create_post.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container"> 
        <div class="row">
          <div class= "col-md-2"> </div>
          <div class="col-md-8">
          <!-- Create Post form -->
          {{wtf.quick_form(post_form)}}
         </div>
         <div clas="col-md-2"> </div>
        </div>
    </div>
    

{% endblock %}

app/templates/blog/post.html
 
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles%} 
    {{ super() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Black+And+White+Picture&family=Charm:wght@700&family=Galada&family=Lakki+Reddy&display=swap" rel="stylesheet">
{% endblock %}



{% block content %}
<div class="container" style="font-family: 'Lakki Reddy', cursive; font-size: 25px;">
    <h2>{{title}}</h2>
    
    <h4>Date published: {{post.posted.strftime('%B %d, %Y')}}</h4>
    <p>
        {{post.body}}

    </p>
    <div>
      <a href="{{url_for('blog.new_comment',id=post.id)}}" class= "btn btn-primary btn-sm"><i class="fas fa-comment"></i> Comment</a>

      
          

          <span class="label label-primary">
              {{ post.comments.count() }} Comments
          </span>
      
      </a>

    </div>

    {% if post.author == current_user %}
    <div>

        <a href="{{url_for('blog.update', post_id = post.id)}}" class= "btn btn-primary btn-sm">Update</a>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete_post">Delete</button>
    </div>

    {% endif %}

</div>
<div class="modal" tabindex="-1" role="dialog" id="delete_post">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Delete Post?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Confirm if you want to the delete post!</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <form action="{{url_for('blog.delete_post', post_id = post.id)}}" method="POST">
                  <input class="btn btn-danger" type="submit" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>



{% endblock  %}

app/templates/blog/view_comments.html
{% extends 'base.html'%}
{% block content %}
    <div class="container">
        <a href="{{url_for('main.index')}}">
            <button type="button" class="btn btn-primary btn-sm">
                    <span class="glyphicon glyphicon-chevron-left" ></span> Back
                </button>
                <h3 style="color:blue;">Comments:</h3>
        </a>
        <div>
            <a href="{{url_for('blog.new_comment',id=id)}}" class= "btn btn-primary btn-sm"><i class="fas fa-comment"></i> Comment</a>
            
            
        <div class="wellbieng">
            <ul>      
        {%for comment in post.comments%}
      
           <li> {{comment.body}}</li>
           <li><button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete_comment">Delete</button></li>

        {%endfor%}
            </ul>
        </div>      
                <span class="label label-primary">
                    {{ post.comments.count() }} Comments
                </span>
            
            </a>
      
        </div>
    </div>
    <div class="modal" tabindex="-1" role="dialog" id="delete_comment">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Delete Comment?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Confirm if you want to the delete commment!</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <form action="{{url_for('blog.delete_comment', id =id)}}" method="POST">
                  <input class="btn btn-danger" type="submit" value="Delete">
              </form>
            </div>
          </div>
        </div>
    </div>

{% endblock %}